version: '3.4'

services:
  apigateway:
    build: ./ApiGateway
    ports:
      - "5000:80"

  filestoringservice:
    build: ./FileStoringService
    ports:
      - "5001:80"

  fileanalysisservice:
    build: ./FileAnalysisService
    ports:
      - "5002:80"
